import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/widgets/Header/Header";
import { cn } from "@/shared/lib/utils";
import { interTight } from "@/shared/lib/fonts";
import Footer from "@/widgets/Footer/Footer";
import Title from "@/widgets/Title/Title";
import { Spacing } from "@/shared/ui/Spacing";
import TronEnergy from "@/widgets/TronEnergy/TronEnergy";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen pt-6 m-0", interTight.variable)}>
        <Header className="app-container " />
        <Spacing size="4xl" direction="vertical" />

        <TronEnergy className="app-container" />

        <main className="app-container flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
